// todoList-Angular/src/app/components/todo-list-item/todo-list-item.component.ts
import { Component, OnInit } from '@angular/core';
import { TasksService} from 'src/app/services/tasks.service';

@Component({
  selector: 'app-todo-list-item',
  templateUrl: './todo-list-item.component.html',
  styleUrls: ['./todo-list-item.component.scss']
})
export class TodoListItemComponent implements OnInit {

  tasks: any;
  hideUpdate:boolean = true;
  myValue;
  model:any = {};

  constructor(
    private tasksService: TasksService,
  ) { }

  ngOnInit(): void {
    this.allTasks()
  }

  editTask(i):void {
    this.hideUpdate = false;
    this.myValue = i;
    this.model.name = this.tasks[i].name;
    this.model.id = this.tasks[i].id;
  }

  // UPDATE TASK
  updateTask() {
    let i = this.myValue;
    this.tasks[i] = this.model;
    let id = this.model.id
    console.log(this.model, id)
    this.tasksService.updateTask(this.model, id)
    .subscribe((task: any) => {
    });
  }

  // DELETE TASK
  removeTask(i) {
    console.log(i, this.tasks[i].id)
    let id = this.tasks[i].id;
    this.tasksService.deleteTask(id)
    .subscribe((product: any) => {
    })
  }

  // SHOW TASKS
  allTasks() {
    this.tasksService.getTasksAll().subscribe((task: any) => {
      this.tasks = task;
    })
  }

  // SHOW TOGGLE
  // showUpdate(){
  //   this.show = !this.show;
  // }
}

<!-- TABLA TASKS -->
<!-- <div class="row">
    <div class="col-sm-7">
      <table class="table table-bordered">
        <tbody>
          <tr *ngFor="let task of tasks; let i = index">
              <td>{{task.name}}</td>
              <td>
                  <button (click)="editTask(i)" class="btn btn-success">
                  Update
                  </button>
                  <button (click)="deleteTask(i)" class="btn btn-danger">
                  Delete
                  </button>
              </td>
          </tr>

        </tbody>
      </table>
    </div>

    <div className="updateForm" [hidden]="hideUpdate">
        <form (submit)="updateTask()">
            <input [(ngModel)]="model.name"  (keyup.enter)="model.name=''" name="name" placeholder="Introduce a task">
            <button type="submit" >Update Todo</button>
        </form>
    </div>
</div> -->

<div>
  <ul class="cards">
      <li class="cards_item" *ngFor="let task of tasks; let i = index">
          <div class="card">
              <div class="card_content">
                  <div class="card_title">{{task.name}}</div> 
                  <div>
                      <input type="checkbox" class="checkComplete" id="complete" name="complete" value="Complete" 
                      [(ngModel)]="task.status">  
                      <label for="complete"> Complete </label><br>  
                  </div>
                                 
                  <div class="btns">
                      <button class="btn btn--block" (click)="editTask(i)"><i class="fas fa-edit"></i></button>
                      <button class="btn btn--block" (click)="removeTask(task.id)"><i class="fas fa-trash-alt"></i></button>
                  </div>

                  <div class='status completed' [hidden]="!task.status" disabled>
                    Completed
                  </div>
                  <div class='status pending' [hidden]="task.status">
                    Pending
                  </div>
              </div>
          </div>
      </li>
  </ul>

  <!-- UPDATE TASK -->
  <div [hidden]="hideUpdate" class="update-form">
      <div class="form-group">
              <label for="title">Title</label>
              <input type="text" class="form-control" id="name"
              required [(ngModel)]="model.name" name="name"
              />
      </div>
      <button on-click="updateTask()" class="btn btn-success">Submit</button>     
  </div>
</div>

// todoList-React/src/components/TodoListItem/TodoListItem.jsx
import React, { Fragment, useState } from 'react';
import './TodoListItem.css';
// import Service from '../../services/axios-service.js';
import { allTasks, deleteTask } from '../../redux/actions/';

const TodoListItem = ({ task }) => {

    const [showResults, setShowResults] = useState(false)
    const onClick = () => setShowResults(true)

    const delete_Task = (id) => {
        console.log(id)
        deleteTask(id)
        allTasks()
    }

    return (
        <Fragment >
            <div className="task" key={task?.id}>
                <p>{task.name}</p>
                <input type="submit" value="Search" onClick={onClick} />
                {/* <button onClick={()=>editTask(i)}><i class="fas fa-edit"></i></button> */}
                <button onClick={()=>delete_Task(task.id)}><i class="fas fa-trash-alt"></i></button>
            </div>

            <div class="card">
                    <div class="card__content">
                        <div class="card__title">{task.name}</div> 
                        <div>
                            <input type="checkbox" class="checkComplete" id="complete" name="complete" value="Complete" 
                            // v-model="task.status" click="checkboxToggle(category)"
                            />  
                            <label for="complete"> Complete </label><br/>  
                        </div>
                                       
                        <div class="btns">
                            {/* <button class="btn btn--block" v-on:click="showUpdate"><i class="fas fa-edit"></i></button>
                            <button class="btn btn--block" v-on:click="removeTask(task._id)"><i class="fas fa-trash-alt"></i></button> */}
                        </div>

                        <div class='status completed' v-show="task.status" disabled>
                            Completed
                        </div>
                        <div class='status pending' v-show="!task.status">
                            Pending
                        </div>
                    </div>
                </div>

            {/* UPDATE TASK  */}
                {/* <div class="update-form">
                    <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" class="form-control" id="name"
                            required name="name"
                            />
                    </div>
                    <button on-click="updateTask()" class="btn btn-success">Submit</button>     
                </div> */}  
        </Fragment>
    )    
}

export default TodoListItem;
