// todoList-Angular/src/app/components/todo-form/todo-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from "@angular/forms";
import { TasksService} from 'src/app/services/tasks.service';

@Component({
  selector: 'app-todo-form',
  templateUrl: './todo-form.component.html',
  styleUrls: ['./todo-form.component.scss']
})
export class TodoFormComponent implements OnInit {

  task: any;
  tasks: any;
  todoTask: {};
  name: "";

  constructor(
    private tasksService: TasksService,
  ) { }

  ngOnInit(): void {
  }

  addTask(task) {
    console.log(task)
    this.todoTask = {
          name: task,
    }
    console.log(this.todoTask)
    this.tasksService.addTask(this.todoTask).subscribe((task: any) => {
    })
  }

  // addTodo(event) {
  //   this.todoObj = {
  //     newTodo: this.newTodo,
  //     completed: false
  //   }
  //   this.todos.push(this.todoObj);
  //   this.newTodo = '';
  //   event.preventDefault();
  // }

}

<div className="createForm">
    <form class="example" (submit)="addTask(name)">
        <input class="form-control" [(ngModel)]="name"  (keyup.enter)="name=''" name="name" placeholder="Introduce a task">
        <button class="btn btn-success" type="submit" >Add Task</button>
    </form>
</div>

// todoList-React/src/components/TodoForm/TodoForm.jsx
import React, { useEffect, useState, Fragment } from 'react';
import './TodoForm.css'
// import Service from '../../services/axios-service.js';
import { addTask, updateTask, allTasks } from '../../redux/actions/';

const TodoForm = (props) => {

    const [name, setName] = useState("");

    useEffect(() => {
    }, [])
    
    const add_Task = event => {
        event.preventDefault();
        let data={
            name: event.target.name.value
        }
        console.log(data)
        addTask(data)
        .then(res => {
            console.log('Task creado con éxito');
            allTasks();
        })
        .catch((error) => {
            console.error(error)
        })
    }

    const handleChange = event =>{
        setName({ name: event.target.name.value});
        console.log(setName)
      }
  
    return (
        <Fragment >
           <form onSubmit={add_Task} className="example">
                <input type="text" name="name" className="form-control" 
                placeholder="Add a new todo..." onChange= {handleChange}/>
                <button type="submit" className="btn btn-success">Add Task</button> 
            </form>
        </Fragment>
    )
       
    
}

export default TodoForm;
